<?php

namespace AppBundle\Repository;

/**
 * CarRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CarRepository extends \Doctrine\ORM\EntityRepository
{

//    public function getCarByModel($make){
//
//return $this
//    ->createQueryBuilder('car')
//    ->groupBy($make)
//    ->addOrderBy('car.model', 'asc')
//    ->addOrderBy('car.travelledDistance', 'desc')
//    ->getQuery()
//    ->getResult();
//    }

    public function getPartsByCar($id)
    {

        return $this->createQueryBuilder('p')
            ->addSelect('car')
            ->from($this->_entityName, 'c')
            ->join('AppBundle/Entity/Part', 'c', 'ON', 'c.parts.id=part.id')
            ->where('cars.id=:car_id')
            ->setParameter('car_id', $id)
            ->getQuery()
            ->getArrayResult();

    }
}
