<?php

namespace AppBundle\Repository;

/**
 * CarsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CarRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAllCars(){
        return $this->createQueryBuilder('car')
            ->orderBy( 'car.model','desc')
            ->orderBy('car.travelledDistance','desc')
//            ->setParameter('sort',$order)
            ->getQuery()
            ->getResult();

    }

}
