<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Customer;

/**
 * CustomerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CustomerRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param string $order
     * @return array
     */
    public function getOrderedCustomers($order){

        if($order === 'ascending'){
            $revisedOrder = 'ASC';
        }elseif ($order === 'descending'){
            $revisedOrder = 'DESC';
        }

        return $this
            ->createQueryBuilder('c')
            ->addOrderBy('c.birthDate',$revisedOrder)
            ->addOrderBy('c.isYoungDriver', 'ASC')
            ->getQuery()
            ->getResult();
    }
}
