<?php

namespace AppBundle\Repository;

/**
 * customerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CustomerRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAllCustomers(string $order){
      return $this->createQueryBuilder('customer')
            ->orderBy( 'customer.birthDate',$order)
//            ->setParameter('sort',$order)
            ->getQuery()
            ->getResult();

    }
    public function customerTotals(int $id)
    {
        return  $this
            ->createQueryBuilder('c')
            ->where('c.id = :id')
            ->setParameter('id', $id)
            ->innerJoin('c.sales','s')
            ->innerJoin('s.car', 'car')
            ->innerJoin('car.parts', 'p')
            ->select('SUM(p.price), SUM(p.price * (1 - s.discount/100))')
            ->getQuery()
            ->getSingleResult();
    }

}
