<?php

namespace AppBundle\Repository;

/**
 * partRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PartRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAllSuppliers(int $position)
    {
        return $this->createQueryBuilder('p')
            ->innerJoin('p.supplier', 's')
            -> where('supplier.isImporter = :position')
            ->setParameter('position',$position)
            ->getQuery()
            ->getResult();
    }
}
