<?php

namespace AppBundle\Repository;

/**
 * supplierRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SupplierRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAllSuppliers(int $position)
    {
        return $this->createQueryBuilder('suppliers')->where('suppliers.isImporter = :isImporter')
            ->setParameter('isImporter',$position)
            ->getQuery()->getResult();
    }

}

// select p.* from parts p inner join suppliers s on s.id = p.supplier_id and isImporter = 1

