<?php

namespace CarDealerBundle\Repository;

use CarDealerBundle\Entity\Cars;

/**
 * CarRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CarRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param string $make
     * @return Cars[]
     */
    public function getCarsByMake($make){
        return $this->createQueryBuilder('cars')
            ->select('cars')
            ->where('cars.make = :make')
            ->addOrderBy('cars.model')
            ->addOrderBy('cars.travelledDistance','DESC')
            ->setParameter('make',$make)
            ->getQuery()->getResult();
    }

    /**
     * @param $id
     * @return mixed
     */
    public function getCarParts($id){
        return $this->createQueryBuilder('cars')
            ->select('cars.parts')
            ->where('cars.id == :id')
            ->setParameter('id',$id)
            ->getQuery()->getResult();
    }


}
