<?php

namespace CarDealerBundle\Repository;

/**
 * CustomerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */

class CustomerRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Get all customers ordered by their birth date ascending or descending.
     * If two customers are born on the same date first print those who are not young drivers (e.g. print experienced drivers first).
     * Show their name, birthdate and whether he is young driver or not.
     *
     * @param string $order
     * @return \Doctrine\ORM\QueryBuilder
     */
    public function getAllCustomersByGivingOrder($order){

        return $this->createQueryBuilder('customers')
            ->addOrderBy('customers.birthDate',$order)
            ->addOrderBy('customers.isYoungDriver')
            ->getQuery()->getResult();
    }
}
