<?php

namespace CarDealerBundle\Repository;

/**
 * SaleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SaleRepository extends \Doctrine\ORM\EntityRepository
{
    public function findDiscountsGreaterThan($percent){
        $em=$this->getEntityManager();
        $qb=$em->createQueryBuilder();

        $query=$qb->select(['s'])
            ->from('CarDealerBundle:Sales','s')
            ->where($qb->expr()->gt('s.discount',$percent))
            ->orderBy('s.discount','DESC')
            ->getQuery();

        return $query->getResult();
    }

    public function findAllByPercent(float $percent){
        return $this->createQueryBuilder('sales')->where('sales.discount=:percent')
            ->setParameter('percent',$percent)
            ->getQuery()->getResult();
    }
}
