<?php

namespace CarDealerBundle\Repository;

/**
 * SupplierRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SupplierRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param string $type
     * @return \Doctrine\ORM\QueryBuilder
     */
    public function getAllSuppliersByType($type){
        $isImporter=false;
        if ($type){
            $isImporter=true;
        }
        return $this->createQueryBuilder('suppliers')->where('suppliers.isImporter = :isImporter')
            ->setParameter('isImporter',$isImporter)
            ->getQuery()->getResult();
    }
}
